# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wktr < Formula
  desc "Manage git worktrees with tmux integration"
  homepage "https://github.com/robinjoseph08/wktr"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robinjoseph08/wktr/releases/download/v0.1.0/wktr_0.1.0_darwin_amd64.tar.gz"
      sha256 "f5b8fc9a44433fe07f4d7fe10c15817a46f486db9e9f9071b500b4b2b7a0349a"

      define_method(:install) do
        bin.install "wktr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robinjoseph08/wktr/releases/download/v0.1.0/wktr_0.1.0_darwin_arm64.tar.gz"
      sha256 "110c7882fbc90c815e0957989a523effce4092853ec2f08a923b18d82e1c05b3"

      define_method(:install) do
        bin.install "wktr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinjoseph08/wktr/releases/download/v0.1.0/wktr_0.1.0_linux_amd64.tar.gz"
      sha256 "272760f6a8ee8457aa23c50a8413f9da66720e1d27b40278fa0a8fc456eeec98"
      define_method(:install) do
        bin.install "wktr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinjoseph08/wktr/releases/download/v0.1.0/wktr_0.1.0_linux_arm64.tar.gz"
      sha256 "cb8ef13878cc89c312da4389a0e69be5959fe314ae9dd327010317b0fa1b1d7a"
      define_method(:install) do
        bin.install "wktr"
      end
    end
  end
end
