# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wktr < Formula
  desc "Manage git worktrees with tmux integration"
  homepage "https://github.com/robinjoseph08/wktr"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robinjoseph08/wktr/releases/download/v0.4.0/wktr_0.4.0_darwin_amd64.tar.gz"
      sha256 "d59a5d56af9a0de1cd79bb6af8ab2a3c72d1cb1fa60793f1b232f3af93e72096"

      define_method(:install) do
        bin.install "wktr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robinjoseph08/wktr/releases/download/v0.4.0/wktr_0.4.0_darwin_arm64.tar.gz"
      sha256 "485ae8bef182babe8f811c430e5942af995014e3b2fcfa70f116ddca800658e0"

      define_method(:install) do
        bin.install "wktr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinjoseph08/wktr/releases/download/v0.4.0/wktr_0.4.0_linux_amd64.tar.gz"
      sha256 "565b41d8fcbb9296facf224bbe098bea24c338c851a308f4cb40b6f8e6c1f6f7"
      define_method(:install) do
        bin.install "wktr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinjoseph08/wktr/releases/download/v0.4.0/wktr_0.4.0_linux_arm64.tar.gz"
      sha256 "fbba72c7a890771e065dcb0177ff447614df5eef77751909587a3301e0fbb2af"
      define_method(:install) do
        bin.install "wktr"
      end
    end
  end
end
